version: "3.1" 

services:

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - my-network

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    networks:
      - my-network

  catalog:
    depends_on:
      - mongo
    container_name: catalog
    image: catalog:1.0
    ports:
      - "4000:4000"
    environment:
      MONGO_URI: mongodb://admin:admin@mongo:27017
    networks:
      - my-network

networks:
  my-network: 


